<a href="https://colab.research.google.com/github/Rowida46/Machine-Learning/blob/master/AI_open.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch
def activation(x):
  return 1+ (1+torch.exp(x))
torch.manual_seed(7)
feature = torch.randn((1,5))   # to give u a tuble sized as u determine
wight = torch.randn_like(feature)
bias = torch.randn((1,1))
print( feature )
print(wight  )
print( bias )

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [18]:
y = activation(torch.sum(feature * wight ) + bias )
y

tensor([[2.1898]])